config/routes.rb
SkillUp::Application.routes.draw do

  resources :mission_embeddings

  root :to => "SkillUp#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :missions
  resources :sessions
  resources :skills
  resources :users do
    resources :user_missions
    resources :user_skill_ratings
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  #field :admin, type: Boolean
  
  #login
  validates_presence_of :username
  validates_uniqueness_of :username
  
  validates_presence_of :email
  validates_uniqueness_of :email
  
  validates_presence_of :password, :on => :create
  has_secure_password
  
  #field :first_name
  #field :last_name
  #field :date_of_birth, :type => Date

  #test geocoding may want to be in a different process
  #field :address
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude, address: :address
  after_validation :geocode
  after_validation :reverse_geocode

  #field :bio

  mount_uploader :avatar, AvatarUploader
  


     

  #Points
  has_many :user_skills, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_skills, allow_destroy: true
  has_many :skills, through: :user_skills
  
  has_many :user_missions, dependent: :destroy, inverse_of: :user, order: "created_at DESC"
  accepts_nested_attributes_for :user_missions, allow_destroy: true
  has_many :missions, through: :user_missions

  #Moderator Status Needs Test
  has_many :user_mission_moderations, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_mission_moderations, allow_destroy: true
  #===========================
  has_many :user_skill_moderations, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_skill_moderations, allow_destroy: true
  ############################

  #friendships
  has_many :user_friendships, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_friendships, allow_destroy: true
  has_many :friends, through: :user_friendships
  has_many :inverse_user_friendships, class_name: "UserFriendship", foreign_key: "friend_id", dependent: :destroy, inverse_of: :friend
  
  #user ratings
  has_many :user_skill_ratings, dependent: :destroy, inverse_of: :rater, foreign_key: "rater_id", order: "created_at DESC"
  accepts_nested_attributes_for :user_skill_ratings, allow_destroy: true
  has_many :ratees, through: :user_skill_ratings
  has_many :inverse_user_skill_ratings, class_name: "UserSkillRating", foreign_key: "ratee_id", dependent: :destroy, inverse_of: :ratee
  
  def total_ability_points
    HashOperations.add_hashes(mission_only_points, ability_only_points)
  end
  
  def skill_only_points
    user_skills.inject(Hash.new(0)) do |skills_agg, user_skill| 
      skills_agg[user_skill.skill.title] += user_skill.points
      skills_agg
    end
  end
  
  def ability_only_points
    user_skills.inject(Hash.new(0)) do |skills_agg, user_skill|
      mod_user_skill_points = HashOperations.multiply_hash_by_value(user_skill.skill.ability_points, user_skill.points)
      HashOperations.add_hashes(skills_agg, mod_user_skill_points)
    end
  end
  
  def mission_only_points
    user_missions.inject(Hash.new(0)) do |skills_agg, user_mission|
      HashOperations.add_hashes(skills_agg, user_mission.mission.ability_points)
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    
    #duplicated in user_missions_controller... maybe should consider refactoring or ajax on page load
    @user_missions_paginator = my_paginate(@user.user_missions, :user_mission_next_element_id)
    
    @user_skill_ratings_paginator = my_paginate(@user.user_skill_ratings, :user_skill_rating_next_element_id)

    respond_to do |format|
      format.js
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id        
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    
    if params[:user].present? && params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.js
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.js
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
private

  def current_resource
    @current_resource ||= User.find(params[:id]) if params[:id]
  end
end

app/views/users/_user_ability_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.object.ability.title %>
  <%= f.label :points %>: <%= f.object.points %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_ability_new_fields.html.erb
<fieldset>
  <%= f.text_field :ability_title, {:class => 'autocomplete_field1', data: { autocomplete_source: abilities_path } } %>
  <%= f.label :points %>: <%= f.text_field :points %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_mission_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.hidden_field :_destroy %>
  <%= f.object.mission.title %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_mission_new_fields.html.erb
<fieldset>
  <%= f.text_field :mission_title, {:class => 'autocomplete_field2', data: {autocomplete_source: missions_path } } %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_skill_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>

  <%= f.object.skill.title %> 
  <%= f.object.points %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_skill_new_fields.html.erb
<fieldset>
  <%= f.text_field :skill_title, {:class => 'autocomplete_field1', data: { autocomplete_source: skills_path } } %>
  <%= f.text_field :points %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_skill_rating_fields.html.erb
<fieldset>
  <% present f.object do |user_skill_rating_presenter|%>
    <%= user_skill_rating_presenter.ratee.username %>
    <%= user_skill_rating_presenter.skill.title %>
    <%= user_skill_rating_presenter.rating %>
  <% end %>
  
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/_user_skill_rating_new_fields.html.erb
<fieldset>
  <%= f.text_field :ratee_username%>
  <%= f.text_field :skill_title%>
  <%= f.star_ratings :rating, 10 %>
  <%= f.hidden_field :_destroy %>

  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= labeled_form_for @user, { class: "edit_user" } do |f| %>
  
  <%= f.error_messages %>
  
  <%= f.text_field :username %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.thumb_image_field :avatar %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.date_select :date_of_birth, :start_year => Date.today.year - 90, :end_year => Date.today.year - 12, :order => [:month, :day, :year]%>
  <%= f.text_field :address %>
  <%= f.text_area :bio, label: "About Me" %>
  
  <%= f.submit %>
<% end %>

<div class="form-actions">
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Sign Up") %></h1>
</div>
<%= labeled_form_for @user do |f| %>
  
  <%= f.error_messages %>
  <%= f.text_field :username %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div id="user_main", class="span7">
    <div id="user_profile">
      <% present @user do |user_presenter|%>
        <%= user_presenter.avatar %>
        <h1><%= user_presenter.username %></h1>
        <dl>
          <dt>Name:</dt>
          <dd><%= user_presenter.full_name %></dd>
          <dt>Age:</dt>
          <dd><%= user_presenter.age %></dd>
          <dt>Location:</dt>
          <dd><%= user_presenter.address %></dd>
          <dt>About Me:</dt>
          <dd><%= user_presenter.bio%></dd>
        </dl>
      <% end %>
    </div>

    <%= content_tag "div", id: "user_missions" do %>
      
      <multiform>
        <%= link_to "Add Task", new_user_user_mission_path(@user), class: "new_link", remote: true %>
        <br/>
        <%= button_tag "Save Tasks", class: "multiSubmitButton btn btn-primary" %>

      </multiform>
      <%= content_tag "div", class: "fields" do %>
        <%= render(@user_missions_paginator.current_elements) %>
      <% end %>
      <% if !@user_missions_paginator.last_page? %>
        <%= link_to 'more tasks', user_user_missions_path(@user, {@user_missions_paginator.next_id_parameter => @user_missions_paginator.next_page_offset_id}), {remote: true, class: "more_fields"} %>
      <% end %>
    <% end %>
  </div>

  <div id="user_side", class="span4">
    <%#thinking about scary/insane refactor %>
    <%= content_tag "div", id: "user_skill_ratings" do %>
      <multiform>
        <%= link_to "Add Skill Rating", new_user_user_skill_rating_path(@user), class: "new_link", remote: true %>
        <br/>
        <%= button_tag "Save Skill Ratings", class: "multiSubmitButton btn btn-primary" %>
      </multiform>
      <%= content_tag "div", class: "fields" do %>
        <%= render(@user_skill_ratings_paginator.current_elements) %>
      <% end %>
      <% if !@user_skill_ratings_paginator.last_page? %>
        <%= link_to 'more ratings', user_user_skill_ratings_path(@user, {@user_skill_ratings_paginator.next_id_parameter => @user_skill_ratings_paginator.next_page_offset_id}), {remote: true, class: "more_fields"} %>
      <% end %>
    <% end %>
    <%= content_tag "div", id: "user_ability_points" do %>
      <h4>Calculated Ability Points</h4>
      <% @user.total_ability_points.sort_by {|k,v| -v}.each do |title, points| %>
        <% present Skill.find_by(title: title) do |skill_presenter| %>
          <%= skill_presenter.link %>: <%= points %><br />
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/update.js.erb
<% if !@user.update_attributes(params[:user]) %>
  alert("Failed to upload painting: <%= j @user.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#avatar_image").replaceWith("<%= j image_tag(@user.avatar.url(:thumb), {id: 'avatar_image'}) %>");
<% end %>