config/routes.rb
SkillUp::Application.routes.draw do

  resources :mission_embeddings

  root :to => "SkillUp#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :missions
  resources :sessions
  resources :skills
  resources :users do
    resources :user_missions
    resources :user_skill_ratings
  end
  

end

app/models/skill.rb
class Skill < ActiveRecord::Base

  validates_presence_of :title
  
  #field :description, type: String



  #needs test
  has_many :user_skills, dependent: :destroy, inverse_of: :skill
  
  has_many :mission_skills, dependent: :destroy, inverse_of: :skill

  has_many :super_embeddings, class_name: "SkillEmbedding", foreign_key: "sub_skill_id", dependent: :destroy, inverse_of: :sub_skill
  has_many :super_skill, through: :super_embeddings, source: :skill

  has_many :user_skill_ratings, dependent: :destroy, inverse_of: :skill
  
  has_many :skill_embeddings, dependent: :destroy, inverse_of: :super_skill, foreign_key: "super_skill_id"
  accepts_nested_attributes_for :skill_embeddings, allow_destroy: true
  validates :skill_embeddings, cyclical_sub_skill_reference: true, unique_sub_skill_reference: true
  has_many :sub_skills, through: :skill_embeddings


     #needs test
  #has_many :friendships
  #has_many :friends, :through => :friendships
  #has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  #has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  #models/friendship.rb
  #belongs_to :user
  #belongs_to :friend, :class_name => "User

  has_many :user_skill_moderations, autosave: true
  
  #Many of these methods desparately need preprocessing

  def self.points_to_level(points)
    self.default_level_maxs.each_with_index.map { |max, i| points >= max ? i + 1: nil }.compact.unshift(0).last
  end

  def self.default_level_maxs
    [1, 5, 10, 20, 50, 150, 500, 2000, 10000, 50000]
  end

  def ability_points
    skill_embeddings.inject({ self.title => 1 }) do |aggregate_hash, embedding|
      modified_embedding = HashOperations.multiply_hash_by_value(embedding.sub_skill.ability_points, embedding.weight)
      HashOperations.add_hashes(aggregate_hash, modified_embedding)
    end
  end

  def all_ancestor_skills
    super_embeddings.inject(Set.new([self])) { |aggregate_set, embedding | aggregate_set | embedding.super_skill.all_ancestor_skills | [embedding.super_skill].to_set }
  end

  def associated_missions
    all_ancestor_skills.map { |skill| skill.mission_skills.map { |mission_skill| mission_skill.mission } }.flatten.to_set
  end

  def all_missions_at_level(level)
    associated_missions.find_all { |mission| self.class.points_to_level(mission.total_ability_points[title]) == level }.to_set
  end
  
  def self.search_titles(skill_title_name)
    Skill.find(:all, :conditions => [ "title ILIKE ?", "%#{skill_title_name.downcase}%"])
  end
  
private
  def lower_title_case
    self.lowercase_title = self.title.downcase
  end  
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    if params[:term].present?
      @skills = Skill.search_titles(params[:term])
    else
      @skills = Skill.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills.map(&:title) }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    @level_dependent_missions = @skill.all_missions_at_level(1).to_a
    if params[:level_mission]
      @level_dependent_missions = @skill.all_missions_at_level(params[:level_mission].to_i).to_a
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
      format.js
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])
    
    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        #debugger
        #errors = @skill.errors
        @skill = Skill.find(params[:id])
        #@skill.errors = errors
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
end

app/views/skills/_form.html.erb
<%= labeled_form_for @skill do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>

  <h2>Sub Skills</h2>
  <%= f.fields_for :skill_embeddings do |skill_embedding_builder| %>
    <%= render 'skill_embeddings/field', f: skill_embedding_builder %>
  <% end %>
  <%= link_to_add_field "Add Sub Skill", f, :skill_embeddings %>  

  <%= f.submit %>
<% end %>

app/views/skills/_sub_embedding_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.object.sub_skill.title %><br />
  <%= f.label :weight %>: <%= f.object.weight %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/skills/_sub_embedding_new_fields.html.erb
<fieldset>
  <%= f.text_field :sub_skill_title, {:class => 'autocomplete_field', data: {autocomplete_source: skills_path } } %><br />
  <%= f.text_field :weight %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/skills/edit.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= labeled_form_for @skill do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>

  <%= f.submit %>
<% end %>

app/views/skills/index.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= link_to skill.title, skill_path(skill) %></td>
        <td><%= skill.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_skill_path(skill), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      skill_path(skill),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_skill_path,
            :class => 'btn btn-primary' %>

app/views/skills/new.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Sign Up") %></h1>
</div>

<%= labeled_form_for @skill do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>

  <%= f.submit %>
<% end %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @skill.title %>
</p>

<p>
  <b>Description:</b>
  <%= @skill.description %>
</p>

<%= content_tag "div", id: "skills", data: {url: skill_url(@skill.id) } do %> <% end %>

<p>
  <b>Related Missions</b>
  <div id="related_slider"> </div>

  <label for="amount"> </label>
  <input type="text", id="amount"></input>

  <ul id="level_dependent_missions_list">
    <%= render @level_dependent_missions %>
  </ul>
</p>

<p>
  <b>Direct Sub Skills:</b><br />
  <% @skill.skill_embeddings.each do |skill_embedding| %>
    <% present skill_embedding do |skill_embedding_presenter| %>
      <%= skill_embedding_presenter.link %>: <%= skill_embedding_presenter.weight %><br />
    <% end %>
  <% end %>
</p>

<p>
  <b>Ability Point Values:</b><br />
  <% @skill.ability_points.sort_by {|k,v| -v}.each do |title, points| %>
    <%= title %>: <%= points %><br />
  <% end %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/skills/show.js.erb
$("#level_dependent_missions_list").html("<%= escape_javascript(render(@level_dependent_missions)) %>");