config/routes.rb
SkillUp::Application.routes.draw do

  resources :mission_embeddings

  root :to => "SkillUp#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :missions
  resources :sessions
  resources :skills
  resources :users do
    resources :user_missions
    resources :user_skill_ratings
  end
  

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  
  validates_presence_of :title
  #field :description, type: String

  has_many :user_missions, dependent: :destroy, inverse_of: :mission

  has_many :mission_skills, dependent: :destroy, inverse_of: :mission
  accepts_nested_attributes_for :mission_skills, allow_destroy: true
  validates :mission_skills, unique_mission_skill_reference: true
  has_many :skills, through: :mission_skills

  has_many :super_embeddings, class_name: "MissionEmbedding", foreign_key: "sub_mission_id", dependent: :destroy, inverse_of: :sub_mission
  has_many :super_mission, through: :super_embeddings, source: :mission

  has_many :mission_embeddings, dependent: :destroy, inverse_of: :super_mission, foreign_key: "super_mission_id"
  accepts_nested_attributes_for :mission_embeddings, allow_destroy: true
  validates :mission_embeddings, cyclical_sub_mission_reference: true, unique_sub_mission_reference: true
  has_many :sub_missions, through: :mission_embeddings

  has_many :user_mission_moderations, dependent: :destroy, inverse_of: :mission
  #Many of these methods desparately need preprocessing

  def total_ability_points
    HashOperations.add_hashes(ability_points, sub_mission_points_only)
  end
  
  def sub_mission_points_only
    mission_embeddings.inject(Hash.new(0)) do |agg_sub_missions, sub_embedding|
      multiplier = sub_embedding.count
      sub_mission_title = sub_embedding.sub_mission.title
      ability_points_multiplied = HashOperations.multiply_hash_by_value(Mission.find_by_title(sub_mission_title).total_ability_points, multiplier)
      HashOperations.add_hashes(agg_sub_missions, ability_points_multiplied)
    end
  end
  
  def ability_points
    skill_points.inject({}) do |agg_hash, (title, points_multiplier)|
      ability_points_multiplied = HashOperations.multiply_hash_by_value(Skill.find_by_title(title).ability_points, points_multiplier)
      HashOperations.add_hashes(agg_hash, ability_points_multiplied)
    end
  end

  def skill_levels
    HashOperations.hmap(total_ability_points) { |name, points| Skill.points_to_level(points) }
  end

  def associated_skill_names
    total_ability_points.map { |name, points| name }.to_set
  end
  
  def skill_points
    mission_skills.inject(Hash.new(0)) do |agg_skills, mission_skill| 
      agg_skills[mission_skill.skill.title] += mission_skill.points
      agg_skills
    end
  end
  
  def self.search_titles(mission_title_name)
    Mission.find(:all, :conditions => [ "title ILIKE ?", "%#{mission_title_name.downcase}%"])
  end
  
private
  def lower_title_case
    self.lowercase_title = self.title.downcase
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  # GET /missions
  # GET /missions.json
  def index
    if params[:term].present?
      @missions = Mission.search_titles(params[:term])
    else
      @missions = Mission.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @missions.map(&:title) }
    end
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
    @mission = Mission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mission }
    end
  end

  # GET /missions/new
  # GET /missions/new.json
  def new
    @mission = Mission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mission }
    end
  end

  # GET /missions/1/edit
  def edit
    @mission = Mission.find(params[:id])
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(params[:mission])

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render json: @mission, status: :created, location: @mission }
      else
        format.html { render action: "new" }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /missions/1
  # PUT /missions/1.json
  def update
    @mission = Mission.find(params[:id])

    respond_to do |format|
      if @mission.update_attributes(params[:mission])
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy

    respond_to do |format|
      format.html { redirect_to missions_url }
      format.json { head :no_content }
    end
  end
end

app/views/missions/_form.html.erb
<%= labeled_form_for @mission do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>

  <h2>Mission Abilities</h2>

  <%= f.fields_for :mission_skills do |mission_skill_builder| %>
    <%= render 'mission_skills/field', f: mission_skill_builder %>
  <% end %>
  <%= link_to_add_field "Add Skill", f, :mission_skills %>

  <h2>Sub Missions</h2>
  <%= f.fields_for :mission_embeddings do |mission_embedding_builder| %>
    <%= render 'mission_embeddings/field', f: mission_embedding_builder %>
  <% end %>
  <%= link_to_add_field "Add Sub Mission", f, :mission_embeddings %>
  
  <%= f.submit %>
<% end %>

app/views/missions/_mission.html.erb
<li>
  <p><%= link_to mission.title, mission_path(mission) %></p>
</li>

app/views/missions/_mission_ability_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.object.ability.title %><br />
  <%= f.label :points %>: <%= f.object.points %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/_mission_ability_new_fields.html.erb
<fieldset>
  <%= f.label :ability_title %><br />
  <%= f.text_field :ability_title, {:class => 'autocomplete_field', data: {autocomplete_source: abilities_path } } %><br />
  <%= f.label :points %>: <%= f.text_field :points %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/_mission_skill_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.object.skill.title %><br />
  <%= f.label :points %>: <%= f.object.points %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/_mission_skill_new_fields.html.erb
<fieldset>
  <%= f.text_field :skill_title, {class: 'autocomplete_field', data: {autocomplete_source: skills_path } }%>
  <%= f.text_field :points %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/_sub_embedding_fields.html.erb
<fieldset>
  <%= f.hidden_field :_id, :value => f.object._id %>
  <%= f.object.sub_mission.title %><br />
  <%= f.label :count %>: <%= f.object.count %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/_sub_embedding_new_fields.html.erb
<fieldset>
  <%= f.text_field :sub_mission_title, {:class => 'autocomplete_field', data: {autocomplete_source: missions_path } } %>
  <%= f.text_field :count %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/missions/edit.html.erb
<%- model_class = Mission -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= labeled_form_for @mission do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>
  
  <%= f.submit %>
<% end %>

app/views/missions/index.html.erb
<%- model_class = Mission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= link_to mission.title, mission_path(mission) %></td>
        <td><%= mission.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mission_path(mission), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mission_path(mission),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mission_path,
            :class => 'btn btn-primary' %>

app/views/missions/new.html.erb
<%- model_class = Mission -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Sign Up") %></h1>
</div>

<%= labeled_form_for @mission do |f| %>

  <%= f.text_field :title%>
  <%= f.text_area :description%>
  
  <%= f.submit %>
<% end %>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @mission.title %>
</p>

<p>
  <b>Description:</b>
  <%= @mission.description %>
</p>

<p>
  <b>Sub Missions:</b><br />
  <% @mission.mission_embeddings.each do |mission_embedding| %>
    <% present mission_embedding do |mission_embedding_presenter| %>
      <%= mission_embedding_presenter.link %>: <%= mission_embedding_presenter.count %><br />
    <% end %>
  <% end %>
</p>

<p>
  <b>Ability Points:</b><br />
  <% @mission.total_ability_points.sort_by {|k,v| -v}.each do |title, points| %>
    <%= title %>: <%= points %><br />
  <% end %>
</p>

<p>
  <b>Skill Levels</b><br />
  <% @mission.skill_levels.sort_by {|k,v| -v}.each do |title, level| %>
    <%= title %>: Level <%= level %><br />
  <% end %>
</p>

<p>
  <b>Skill Points on Mission:</b><br />
  <% @mission.mission_skills.each do |mission_skill| %>
    <% present mission_skill do |mission_skill_presenter| %>
      <%= mission_skill_presenter.link %>: <%= mission_skill_presenter.points %><br />
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>