config/routes.rb
SkillUp::Application.routes.draw do

  resources :mission_embeddings

  root :to => "SkillUp#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :missions
  resources :sessions
  resources :skills
  resources :users do
    resources :user_missions
    resources :user_skill_ratings
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillUp</title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

  <%= yield %>
<%
=begin %>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Skill Up</a>
          <div class="nav-collapse">
            <ul class="nav"> 
              <% if current_user %>
                <li><%= link_to "#{current_user.email} Profile", user_path(current_user)%></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
                <li><%= link_to "Log Out", logout_path%></li>
              <% else %>
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div id="container">
      
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      
      <div class="row">
        <div class="span1"></div>
        <div class="span11"><%= yield %></div>
      </div>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
          <h2>About Us</h2>
          We are a social site trying to quantify what skills and abilities are in society.
          Doing this we hope to help people learn how they can attain mastery and teach others skills.  
          We also hope to help people find skills unknown talents and possible new hobbies and passions.
      </div>
    </footer>
<%
=end %>
  </body>
</html>